define([
  './home/HomePage',
  './insert-coin/InsertCoinPage',
  './select-coinslot/SelectCoinslotPage',
  './buy-eload/BuyEloadPage.js',
  './buy-wifi-buttons/BuyWifiButtonsComponent',
  './more-buttons/MoreButtons',
  './receipt-page/ReceiptPage',
  './view-vouchers/ViewVouchers',
  './view-rates/ViewRates'
]);
