define([
  './home/HomePage',
  './insert-coin/InsertCoinPage',
  './select-coinslot/SelectCoinslotPage.js',
  './buy-eload/BuyEloadPage.js',
  './buy-wifi-buttons/BuyWifiButtonsComponent',
  './more-buttons/MoreButtons',
  './receipt-page/ReceiptPage',
  './view-vouchers/ViewVouchers',
  './view-rates/ViewRates',
  './view-account/ViewAccount',
  './gcash-cashin/GcashCashin'
]);
