define([
  './home/HomePage',
  './insert-coin/InsertCoinPage',
  './select-coinslot/SelectCoinslotPage.js',
  './buy-wifi-or-eload/BuyWifiOrEloadComponent',
  './buy-wifi-buttons/BuyWifiButtonsComponent',
  './more-buttons/MoreButtons',
  './receipt-page/ReceiptPage'
]);
