define(function () {

  // https://stackoverflow.com/a/7053197
  
  var ready = function() {function q() {if(!b.isReady) {try{document.documentElement.doScroll('left');}catch(a) {setTimeout(q,1); return;}b.ready();}}var h,e,t = {'[object Boolean]':'boolean','[object Number]':'number','[object String]':'string','[object Function]':'function','[object Array]':'array','[object Date]':'date','[object RegExp]':'regexp','[object Object]':'object'},b = {isReady:!1,readyWait:1,holdReady:function(a) {a ? b.readyWait++ : b.ready(!0);},ready:function(a) {if(!0 === a && !--b.readyWait || !0 !== a && !b.isReady) {if(!document.body) {return setTimeout(b.ready,
    1);}b.isReady = !0; !0 !== a && --b.readyWait > 0 || h.resolveWith(document,[b]);}},bindReady:function() {if(!h) {h = b._Deferred(); if(document.readyState === 'complete')return setTimeout(b.ready,1); if(document.addEventListener)document.addEventListener('DOMContentLoaded',e,!1),window.addEventListener('load',b.ready,!1); else if(document.attachEvent) {document.attachEvent('onreadystatechange',e); window.attachEvent('onload',b.ready); var a = !1; try{a = window.frameElement == null;}catch(c) {}document.documentElement.doScroll &&
a && q();}}},_Deferred:function() {var a = [],c,k,l,g = {done:function() {if(!l) {var f = arguments,d; if(c) {var m = c; c = 0;}var n = 0; for(d = f.length; n < d; n++) {var p = f[n]; var r = b.type(p); r === 'array' ? g.done.apply(g,p) : r === 'function' && a.push(p);}m && g.resolveWith(m[0],m[1]);}return this;},resolveWith:function(f,d) {if(!l && !c && !k) {d = d || []; k = 1; try{for(;a[0];)a.shift().apply(f,d);}finally{c = [f,d],k = 0;}}return this;},resolve:function() {g.resolveWith(this,arguments); return this;},isResolved:function() {return!(!k && !c);},cancel:function() {l =
1; a = []; return this;}}; return g;},type:function(a) {return a == null ? String(a) : t[Object.prototype.toString.call(a)] || 'object';}}; document.addEventListener ? e = function() {document.removeEventListener('DOMContentLoaded',e,!1); b.ready();} : document.attachEvent && (e = function() {document.readyState === 'complete' && (document.detachEvent('onreadystatechange',e),b.ready());}); return function(a) {b.bindReady(); b.type(a); h.done(a);};}();
  return ready;
});
